### ISSUE TITLE
Update the cpp-tutorials to work with the latest version of FIFE

### ISSUE THREAD

**Issue by prock-fife** [fifengine/cpp-tutorials#1]
The cpp-tutorials were written for an older version of FIFE and need to be updated to work with fife trunk.

**Comment by prock-fife** [comment]
Assigning to vtchill.   I believe this has been worked out but I'll let him close the issue.

**Comment by erbridge** [comment]
I'd be really interested in the progress of this.

The latest version of FIFE doesn't appear to have an `ext` directory, so I can't install `guichan` to build the tutorials.

**Comment by stubb** [comment]
Instead of guichan you need fifechan now for the current version of fife.

**Comment by erbridge** [comment]
Apparently the tutorials are built with guichan:

```
[ 16%] Building CXX object CMakeFiles/Tutorial1.dir/Game.cpp.o
<cpp-tutorials>/src/tutorial_1/Game.cpp:20:40: fatal error: gui/guichan/guichanmanager.h: No such file or directory
compilation terminated.
make[2]: *** [CMakeFiles/Tutorial1.dir/Game.cpp.o] Error 1
make[1]: *** [CMakeFiles/Tutorial1.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by vtchill** [comment]
I will look into fixing this issue and report back with progress/information.

**Comment by prock-fife** [comment]
Latest merge has taken care of this.   This now works with FIFE master.
