### ISSUE TITLE
Access to Appveyor

### ISSUE THREAD

**Issue by prock-fife** [fifengine/cpp-tutorials#10]
I get an "access denied" message when going here:

https://ci.appveyor.com/project/fifengine-cpp-tutorials/fifengine-cpp-tutorials/branch/master

**Comment by jakoch** [comment]
Well, i can't change that and activate Appveyor here, because i don't have permissions. 
Your task! Or we have to link the Appveyor builds of my fork instead, like on the other repos.

https://ci.appveyor.com/project/jakoch/fifengine-cpp-tutorials/branch/master

**Comment by prock-fife** [comment]
I'm not familiar with appveyor.  I will need to look at activating it.
