### ISSUE TITLE
Replace assets with known good assets

### ISSUE THREAD

**Issue by prock-fife** [fifengine/cpp-tutorials#16]
The assets used in these tutorials to something known to be good (the stuff from fife_test should be fine).

**Comment by prock-fife** [comment]
Related to #8

**Comment by LinuxDonald** [comment]
Where can i find this stuff? And can i fix the maps with the fife editor?

**Comment by prock-fife** [comment]
You might be able to steal maps and assets from here: https://github.com/fifengine/fifengine/tree/master/tests/fife_test

I'm not sure on the support of the C++ map loaders though.
